// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-WbVw6anRljMI2e9MeO7qv3gD7VFnJww',
    appId: '1:794105556009:web:7f5b4ed07893dfa96dc038',
    messagingSenderId: '794105556009',
    projectId: 'task-app-6f5f3',
    authDomain: 'task-app-6f5f3.firebaseapp.com',
    storageBucket: 'task-app-6f5f3.appspot.com',
    measurementId: 'G-X70G2E26RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIfS3Bm8df1LsvTct2iIU5UFYotHvC2c',
    appId: '1:794105556009:android:a54427e6ede4c7af6dc038',
    messagingSenderId: '794105556009',
    projectId: 'task-app-6f5f3',
    storageBucket: 'task-app-6f5f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkCIJpcC-9gHIg1B2pYCrO0mrzqF8egy8',
    appId: '1:794105556009:ios:5b79a24613f97aa56dc038',
    messagingSenderId: '794105556009',
    projectId: 'task-app-6f5f3',
    storageBucket: 'task-app-6f5f3.appspot.com',
    iosBundleId: 'com.example.taskList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkCIJpcC-9gHIg1B2pYCrO0mrzqF8egy8',
    appId: '1:794105556009:ios:5b79a24613f97aa56dc038',
    messagingSenderId: '794105556009',
    projectId: 'task-app-6f5f3',
    storageBucket: 'task-app-6f5f3.appspot.com',
    iosBundleId: 'com.example.taskList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-WbVw6anRljMI2e9MeO7qv3gD7VFnJww',
    appId: '1:794105556009:web:8aa750af7966d2a16dc038',
    messagingSenderId: '794105556009',
    projectId: 'task-app-6f5f3',
    authDomain: 'task-app-6f5f3.firebaseapp.com',
    storageBucket: 'task-app-6f5f3.appspot.com',
    measurementId: 'G-C7CB7WJT3F',
  );
}
